# Generated by Django 2.2.6 on 2019-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=64)),
                ('game_description', models.CharField(max_length=240, null=True)),
                ('cover', models.ImageField(upload_to='images/')),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
