# Generated by Django 2.2.6 on 2019-10-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='was_streamed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/covers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
