# Generated by Django 2.2.6 on 2019-10-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191018_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='images/none/default.png', upload_to='images/covers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.CharField(default='Huntress hunts for the booty', max_length=240),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='Booty Huntress IV', max_length=64),
        ),
    ]
