# Generated by Django 2.2.6 on 2019-10-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191018_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(max_length=64),
        ),
    ]
