# Generated by Django 2.2.7 on 2020-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_when_streamed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stream_list',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
